; SAM Coupé - All ports
; ---------------------
;
; Include this file to include all of the others.
;
; Author: Simon Cooke (spectecjr@gmail.com)
; Licensed under the MIT license (see LICENSE file).

include "base_l.z80"
include "colours_l.z80"
include "comms_l.z80"
include "disk_l.z80"
include "joystick_l.z80"
include "keyboard_l.z80"
include "lightpen_l.z80"
include "sound_l.z80"
include "externalmemory_l.z80"
include "realtimeclock_l.z80"
